//
// Created by nava on 16/03/23.
//

#ifndef ATPBTEXTVERSION_ATPBTEXTVERSION_H
#define ATPBTEXTVERSION_ATPBTEXTVERSION_H

enum
{
    MAX_NUMBER_OF_ALIEN_BOMBS = 1,
    PLAYER_SPRITE_WIDTH = 10,
    PLAYER_SPRITE_HEIGHT = 4,
    NOT_IN_PLAY = -1,
    PLAYER_MISSILE_SPEED = 1,
    FPS = 20,
    INVADER_SPRITE_WIDTH = 7,
    INVADER_SPRITE_HEIGHT = 4,
    INVADER_MISSILE_SPEED = 1,
};

#endif //ATPBTEXTVERSION_ATPBTEXTVERSION_H
